
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMFUploadService", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
@XmlSeeAlso({
    com.bseindia.bsestarmfdemo._2016._01.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactoryMFUpload.class
})
public interface IMFUploadService {


    /**
     * 
     * @param passKey
     * @param userId
     * @param memberId
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/getPassword")
    @WebResult(name = "getPasswordResult", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
    @RequestWrapper(localName = "getPassword", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/", className = "com.bseindia.bsestarmfdemo._2016._01.GetPassword")
    @ResponseWrapper(localName = "getPasswordResponse", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/", className = "com.bseindia.bsestarmfdemo._2016._01.GetPasswordResponse")
    public String getPassword(
        @WebParam(name = "UserId", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String userId,
        @WebParam(name = "MemberId", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String memberId,
        @WebParam(name = "Password", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String password,
        @WebParam(name = "PassKey", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String passKey);

    /**
     * 
     * @param encryptedPassword
     * @param flag
     * @param param
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MFAPI", action = "http://bsestarmfdemo.bseindia.com/2016/01/IMFUploadService/MFAPI")
    @WebResult(name = "MFAPIResult", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
    @RequestWrapper(localName = "MFAPI", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/", className = "com.bseindia.bsestarmfdemo._2016._01.MFAPI")
    @ResponseWrapper(localName = "MFAPIResponse", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/", className = "com.bseindia.bsestarmfdemo._2016._01.MFAPIResponse")
    public String mfapi(
        @WebParam(name = "Flag", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String flag,
        @WebParam(name = "UserId", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String userId,
        @WebParam(name = "EncryptedPassword", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String encryptedPassword,
        @WebParam(name = "param", targetNamespace = "http://bsestarmfdemo.bseindia.com/2016/01/")
        String param);

}
