
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MFUploadService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://bsestarmfdemo.bseindia.com/MFUploadService/MFUploadService.svc?wsdl")
public class MFUploadService
    extends Service
{

    private final static URL MFUPLOADSERVICE_WSDL_LOCATION;
    private final static WebServiceException MFUPLOADSERVICE_EXCEPTION;
    private final static QName MFUPLOADSERVICE_QNAME = new QName("http://tempuri.org/", "MFUploadService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://bsestarmfdemo.bseindia.com/MFUploadService/MFUploadService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MFUPLOADSERVICE_WSDL_LOCATION = url;
        MFUPLOADSERVICE_EXCEPTION = e;
    }

    public MFUploadService() {
        super(__getWsdlLocation(), MFUPLOADSERVICE_QNAME);
    }

    public MFUploadService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MFUPLOADSERVICE_QNAME, features);
    }

    public MFUploadService(URL wsdlLocation) {
        super(wsdlLocation, MFUPLOADSERVICE_QNAME);
    }

    public MFUploadService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MFUPLOADSERVICE_QNAME, features);
    }

    public MFUploadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MFUploadService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IMFUploadService
     */
    @WebEndpoint(name = "WSHttpBinding_IMFUploadService")
    public IMFUploadService getWSHttpBindingIMFUploadService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IMFUploadService"), IMFUploadService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMFUploadService
     */
    @WebEndpoint(name = "WSHttpBinding_IMFUploadService")
    public IMFUploadService getWSHttpBindingIMFUploadService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IMFUploadService"), IMFUploadService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MFUPLOADSERVICE_EXCEPTION!= null) {
            throw MFUPLOADSERVICE_EXCEPTION;
        }
        return MFUPLOADSERVICE_WSDL_LOCATION;
    }

}
