
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StarMFPaymentGatewayService", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://www.bsestarmf.in/StarMFPaymentGatewayService/StarMFPaymentGatewayService.svc?singleWsdl")
public class StarMFPaymentGatewayService
    extends Service
{

    private final static URL STARMFPAYMENTGATEWAYSERVICE_WSDL_LOCATION;
    private final static WebServiceException STARMFPAYMENTGATEWAYSERVICE_EXCEPTION;
    private final static QName STARMFPAYMENTGATEWAYSERVICE_QNAME = new QName("http://tempuri.org/", "StarMFPaymentGatewayService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.bsestarmf.in/StarMFPaymentGatewayService/StarMFPaymentGatewayService.svc?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STARMFPAYMENTGATEWAYSERVICE_WSDL_LOCATION = url;
        STARMFPAYMENTGATEWAYSERVICE_EXCEPTION = e;
    }

    public StarMFPaymentGatewayService() {
        super(__getWsdlLocation(), STARMFPAYMENTGATEWAYSERVICE_QNAME);
    }

    public StarMFPaymentGatewayService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STARMFPAYMENTGATEWAYSERVICE_QNAME, features);
    }

    public StarMFPaymentGatewayService(URL wsdlLocation) {
        super(wsdlLocation, STARMFPAYMENTGATEWAYSERVICE_QNAME);
    }

    public StarMFPaymentGatewayService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STARMFPAYMENTGATEWAYSERVICE_QNAME, features);
    }

    public StarMFPaymentGatewayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StarMFPaymentGatewayService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IStarMFPaymentGatewayService"), IStarMFPaymentGatewayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IStarMFPaymentGatewayService"), IStarMFPaymentGatewayService.class, features);
    }

    /**
     * 
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService1")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService1() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IStarMFPaymentGatewayService1"), IStarMFPaymentGatewayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFPaymentGatewayService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFPaymentGatewayService1")
    public IStarMFPaymentGatewayService getWSHttpBindingIStarMFPaymentGatewayService1(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IStarMFPaymentGatewayService1"), IStarMFPaymentGatewayService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STARMFPAYMENTGATEWAYSERVICE_EXCEPTION!= null) {
            throw STARMFPAYMENTGATEWAYSERVICE_EXCEPTION;
        }
        return STARMFPAYMENTGATEWAYSERVICE_WSDL_LOCATION;
    }

}
