
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StarMFWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.bsestarmf.in/StarMFWebService/StarMFWebService.svc?wsdl")
public class StarMFWebService
    extends Service
{

    private final static URL STARMFWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException STARMFWEBSERVICE_EXCEPTION;
    private final static QName STARMFWEBSERVICE_QNAME = new QName("http://tempuri.org/", "StarMFWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.bsestarmf.in/StarMFWebService/StarMFWebService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STARMFWEBSERVICE_WSDL_LOCATION = url;
        STARMFWEBSERVICE_EXCEPTION = e;
    }

    public StarMFWebService() {
        super(__getWsdlLocation(), STARMFWEBSERVICE_QNAME);
    }

    public StarMFWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STARMFWEBSERVICE_QNAME, features);
    }

    public StarMFWebService(URL wsdlLocation) {
        super(wsdlLocation, STARMFWEBSERVICE_QNAME);
    }

    public StarMFWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STARMFWEBSERVICE_QNAME, features);
    }

    public StarMFWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StarMFWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStarMFWebService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFWebService")
    public IStarMFWebService getWSHttpBindingIStarMFWebService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IStarMFWebService"), IStarMFWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStarMFWebService
     */
    @WebEndpoint(name = "WSHttpBinding_IStarMFWebService")
    public IStarMFWebService getWSHttpBindingIStarMFWebService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IStarMFWebService"), IStarMFWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STARMFWEBSERVICE_EXCEPTION!= null) {
            throw STARMFWEBSERVICE_EXCEPTION;
        }
        return STARMFWEBSERVICE_WSDL_LOCATION;
    }

}
