
package com.ndml.kra.pan.webservice.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PANServiceImplService", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", wsdlLocation = "https://kra.ndml.in/sms-ws/PANServiceImplService/PANServiceImplService.wsdl")
public class PANServiceImplService
    extends Service
{

    private final static URL PANSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PANSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PANSERVICEIMPLSERVICE_QNAME = new QName("http://service.webservice.pan.kra.ndml.com/", "PANServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://kra.ndml.in/sms-ws/PANServiceImplService/PANServiceImplService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PANSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PANSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PANServiceImplService() {
        super(__getWsdlLocation(), PANSERVICEIMPLSERVICE_QNAME);
    }

    public PANServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PANSERVICEIMPLSERVICE_QNAME, features);
    }

    public PANServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PANSERVICEIMPLSERVICE_QNAME);
    }

    public PANServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PANSERVICEIMPLSERVICE_QNAME, features);
    }

    public PANServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PANServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PANServiceImpl
     */
    @WebEndpoint(name = "PANServiceImplPort")
    public PANServiceImpl getPANServiceImplPort() {
        return super.getPort(new QName("http://service.webservice.pan.kra.ndml.com/", "PANServiceImplPort"), PANServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PANServiceImpl
     */
    @WebEndpoint(name = "PANServiceImplPort")
    public PANServiceImpl getPANServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.webservice.pan.kra.ndml.com/", "PANServiceImplPort"), PANServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PANSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PANSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PANSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
