
package com.ndml.kra.pan.webservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PANServiceImpl", targetNamespace = "http://service.webservice.pan.kra.ndml.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PANServiceImpl {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "panInquiryDetails", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.PanInquiryDetails")
    @ResponseWrapper(localName = "panInquiryDetailsResponse", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.PanInquiryDetailsResponse")
    @Action(input = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/panInquiryDetailsRequest", output = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/panInquiryDetailsResponse")
    public String panInquiryDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "panDownloadDetails", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.PanDownloadDetails")
    @ResponseWrapper(localName = "panDownloadDetailsResponse", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.PanDownloadDetailsResponse")
    @Action(input = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/panDownloadDetailsRequest", output = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/panDownloadDetailsResponse")
    public String panDownloadDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "panDownloadDetailsComplete", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.PanDownloadDetailsComplete")
    @ResponseWrapper(localName = "panDownloadDetailsCompleteResponse", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.PanDownloadDetailsCompleteResponse")
    @Action(input = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/panDownloadDetailsCompleteRequest", output = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/panDownloadDetailsCompleteResponse")
    public String panDownloadDetailsComplete(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPasscode", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.GetPasscode")
    @ResponseWrapper(localName = "getPasscodeResponse", targetNamespace = "http://service.webservice.pan.kra.ndml.com/", className = "com.ndml.kra.pan.webservice.service.GetPasscodeResponse")
    @Action(input = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/getPasscodeRequest", output = "http://service.webservice.pan.kra.ndml.com/PANServiceImpl/getPasscodeResponse")
    public String getPasscode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
